### ISSUE TITLE
BUG: Export, edit, import template doesn't work with type = "select" (and maybe others)

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#284] opened 2024-09-30 18:44 UTC
Using attached template and data:

1. Export template
2. Make a minor edit to a select object (e.g., add the 2 in ancient Mesopotamia below). 
3. Import template
4. Screen blanks and the following errors are seen
5. The template no-longer has historical context and some other recent fields

**Template:**
[Archive 2.zip](https://github.com/user-attachments/files/17194847/Archive.2.zip)

**Error:**
<img width="426" alt="Screenshot 2024-09-30 at 2 35 33 PM" src="https://github.com/user-attachments/assets/0f604c6b-97f3-48be-8225-f1334a1988ca">

**HistoricalContext definition:**
`[nodeDefs.historicalcontext]
type = "select"
displayLabel = "Historical context"
exportLabel = "Historical context"
help = "What's the historical context for this social role? (This might mean duplicate nodes.)"
includeInGraphTooltip = true
isProvenance = false
hidden = false

  [[nodeDefs.historicalcontext.options]]
  color = "#eeeeee"
  label = ""
  replacement = ""
  delete = false

  [[nodeDefs.historicalcontext.options]]
  color = "#eeeeee"
  label = "Modern Alabama"
  replacement = ""
  delete = false

  [[nodeDefs.historicalcontext.options]]
  color = "#eeeeee"
  label = "Ancient Mesopotamia 2"
  replacement = ""
  delete = false`

**Comment by benloh** [comment] 2024-09-30 21:10
See #248.  Template exporting and importing is probably broken.

**Comment by benloh** [comment] 2024-12-21 00:18
@jdanish please see if `dev-bl/fix-export` also fixes this. PR #308.

**Comment by jdanish** [comment] 2024-12-21 12:54
Unfortunately, no. Though I think it is a different error. For this, I opened a network, exported the template, changed one field  label (website to website 2) and then imported and got a blank screen with this error.  Once this is addressed I can try and test different attribute types (this one happened to be markdown).

<img width="1696" alt="Screenshot 2024-12-21 at 7 50 19 AM" src="https://github.com/user-attachments/assets/df8f8322-1174-4ad7-9260-8ecb684e3c44" />

**Comment by jdanish** [comment] 2024-12-21 13:25
Update, reported error was using the attached network. With a brand new network, this appears to work OK.

[CRLT People.zip](https://github.com/user-attachments/files/18218633/CRLT.People.zip)

**Comment by benloh** [comment] 2024-12-21 21:27
Issue moved to #311

**Comment by benloh** [comment] 2024-12-22 22:15
Should be fixed with c0ad2541a84fe12ac999e5056d8f5d895d1fa89e

**Comment by jdanish** [comment] 2024-12-22 22:36
Created a network, added a select tag, though this also happens with a string or markdown called "website":

> [nodeDefs.type]
> type = "select"
> displayLabel = "Tag"
> exportLabel = "Tag"
> help = "Select a category"
> includeInGraphTooltip = true
> isProvenance = false
> hidden = false
> 
>   [[nodeDefs.tag.options]]
>   color = "#eeeeee"
>   label = ""

Anyhow, load network. Looks fine. Export template. Re-import without changing. Blank screen with error:

Update: tested with tag, not type - copied wrong one.

<img width="1694" alt="Screenshot 2024-12-22 at 5 35 02 PM" src="https://github.com/user-attachments/assets/a0545dbd-2466-4791-9d62-665204a4e934" />

**Comment by jdanish** [comment] 2024-12-22 22:43
Update: If I go the opposite direction - create a template without the non-normal field (e.g., tag, website, etc.) then export, add that field, import...  no error, but the new field does not appear. It appears that default fields like notes are being read in but not arbitrary fields?

**Comment by benloh** [comment] 2024-12-22 23:37
@jdanish weird this should be fixed.

> Created a network, added a select tag, though this also happens with a string or markdown called "website":
> 
> > [nodeDefs.type]
> > type = "select"
> > displayLabel = "Tag"
> > exportLabel = "Tag"
> > help = "Select a category"
> > includeInGraphTooltip = true
> > isProvenance = false
> > hidden = false
> > [[nodeDefs.tag.options]]
> > color = "#eeeeee"
> > label = ""

Shouldn't that first line be 
```
[nodeDefs.tag]  // `tag` not `type`
```

**Comment by jdanish** [comment] 2024-12-22 23:39
Yeah, tested with the right one but copied wrong one. Did I need to do npm ci maybe? Trying that now.

**Comment by benloh** [comment] 2024-12-22 23:40
You did a fetch and pull?

**Comment by jdanish** [comment] 2024-12-22 23:40
Yup

**Comment by jdanish** [comment] 2024-12-22 23:46
Just tried clearing cache by hand and same problem. Is it possible you didn't commit something?  This is what I see...

<img width="1311" alt="Screenshot 2024-12-22 at 6 46 29 PM" src="https://github.com/user-attachments/assets/4eb8be24-72aa-466e-a8b7-16648154aea8" />

**Comment by benloh** [comment] 2024-12-23 00:17
Hmm...looks like the JSON editor is clobbering template loading...

**Comment by benloh** [comment] 2024-12-23 00:21
I probably need to properly get rid of the fricken JSON editor...

**Comment by jdanish** [comment] 2024-12-23 00:26
Ok by me to get rid of it, but how are you testing? Console commands? If so I’ll use that.

**Comment by benloh** [comment] 2024-12-23 00:31
The problem is that when the changed template is uploaded, the JSON editor tries to load the new template, but the old schemas override the new template definitions that are being introduced.  So then when you click "Save Changes" the old schema is basically overwritten.  So some template changes were working because they mapped to existing schemas.

The way to do this currently is:
1. Export template
2. Quit app
3. Edit the template
4. Put the new template in `/runtime`
5. Start the app again

This insures that you load the app with the latest template without going through the JSON Editor

**Comment by jdanish** [comment] 2024-12-23 00:33
Ahh but on DO that only works for people with ftp access.  Right now kalani and i are doing 98% of edits so removing the json editor from the mix is ok.

**Comment by benloh** [comment] 2024-12-23 00:34
Heh we had already noted this: https://github.com/netcreateorg/netcreate-itest/issues/115

**Comment by jdanish** [comment] 2024-12-23 00:42
Right now, the only thing other people use are the node / edge editors, not
the full edit. However, if it is easier to remove the entire editor or make
it just a basic text editor then that's 100% AOK for now.

**Comment by benloh** [comment] 2024-12-23 01:01
To close this off...there were three problems.
1.  Exporting and re-importing templates were broken due to hidden fields not being exported. #296 #297.  Fixed with #308.
2. Exporting and re-importing were causing errors due to interim state updates as templates transitioned from one type to another #311 [# 284 comment](https://github.com/netcreateorg/netcreate-itest/issues/284#issuecomment-2558114447).  Fixed with #308 in c0ad2541a84fe12ac999e5056d8f5d895d1fa89e.
3. Importing a template with custom fields would cause JSON Editor to revert to predefined schemas, removing the custom fields.  The main comment in this issue (#284) is an example of the error.  Issue #115 is the proper description.  

Closing this and moving solution to #115.

**Closed as completed by benloh** 2024-12-23 01:01 UTC
Labels: bug, p4 must have, template

**Comment by benloh** [comment] 2024-12-23 18:47
> Created a network, added a select tag, though this also happens with a string or markdown called "website":
> 
> > [nodeDefs.type]
> > type = "select"
> > displayLabel = "Tag"
> > exportLabel = "Tag"
> > help = "Select a category"
> > includeInGraphTooltip = true
> > isProvenance = false
> > hidden = false
> > [[nodeDefs.tag.options]]
> > color = "#eeeeee"
> > label = ""
> 
> Anyhow, load network. Looks fine. Export template. Re-import without changing. Blank screen with error:

@jdanish I've closed this issue to clean things up.  But you might do a test with `dev-next` to make sure.  There were a multiple inter-related issues.  Hopefully they're finally cleaned up.

**Comment by jdanish** [comment] 2024-12-23 19:03
Looks fixed in dev-next thanks.
