### ISSUE TITLE
Comment does not open

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#245] opened 2024-08-31 19:11 UTC
Currently, if you log in and click on a comment via the nodes table, it appears to lock. That is, log in, open nodes table, sort by comments so that the highest number is on the top. Click on comment and nothing happens. View node and click on comment. Nothing happens. If you reload, go directly to that node, it appears to open.

**Comment by jdanish** [comment] 2024-08-31 19:13
Log file from the duplicate network I made to test this...
[2024-08312024-0831-log-182834.txt](https://github.com/user-attachments/files/16825760/2024-08312024-0831-log-182834.txt)

**Comment by benloh** [comment] 2024-09-06 16:03
The comment button is sometimes not registering clicks at all...whether in the node editor or the node table.

**Comment by benloh** [comment] 2024-09-07 13:07
NOTE: This is happening with the `dev` branch PRE-resizable table: babb3a3e246b3dbfe2d84d6b395cfc5b8c202827 and there have been significant changes to tables and comments in the `resizable-table` branch.

The error is happening mostly when the table is sorted repeatedly on the comment column.

Testing with the current `resizable-table` branch...
...can't reproduce error in `resizable-table`branch 25b76b5119bc828366db9484f4c56a9d8305410b

Won't fix for now.

**Comment by benloh** [comment] 2024-09-07 13:09
@jdanish letting you know that this doesn't seem to be a problem with the resizable table branch so the current plan is not to do anything about it unless you can find a reproducible error in resizable-tablebranch 25b76b5119bc828366db9484f4c56a9d8305410b

**Closed as completed** 2024-09-20 14:26 UTC
Labels: wontfix
